---
title: "High level structure"
output: html_document
date: "2023-01-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

In randomized clinical trials the homogeneity of treatment effect estimates in subgroups is studied using forest plots. However, the naive way of estimating  these subgroup treatment effects has to be interpreted with great care because of the smaller sample size of the subgroups (leading to large variability of the estimated effects) and the frequently large number of investigated subgroups. 

Subgroup treatment effect estimates with a lower mean-square error based on frequentist and Bayesian shrinkage have been studied. In this package we are implementing the functions needed to apply these shrinkage methods to data sets with survival and binary outcomes.


## Treatment effect estimation methods

### Naive Overall Population Model Estimation

To estimate the treatment effect of the different subgroups we can always consider the naive estimate based on the overall population. This will lead to the same treatment effect for all the subgroups (the naive treatment effect obtained from all the population).

In our package this overall population treatment effect can be estimated using the function `naivepop`.

Given the response and the treatment variables, this function fits a model with all the data giving us the information to obtain an estimate of the treatment effects.

In the case of time-to-event data we will fit a Cox regression with a censoring variable, with the treatment as explanatory variable and with the time to event as response variable. By taking the exponential of the coefficient associated with treatment we obtain the hazard ratio. 

In the case of data with binary outcome we will fit a logistic regression model with treatment as explanatory variable and with the binary considered variable as response. The coefficient associated with treatment can be interpreted as the log odds ratio.


### Naive Model Estimation
The traditional way to estimate the treatment effect of the different subgroups is what we call the naive estimation.

In our package this naive treatment effect estimation can be performed using the function `naive`.

Given the response, treatment and subgroup variables, this function fits a model in each one of the data sets corresponding to a specific subgroup (for example if the subgroup that we are studying is Sex=Female we are going to fit the model just with the data of the patients that are female) in order to obtain the necessary information to estimate the specific treatment effects.

In the case of time-to-event data, for each one of the subgroup-specific data sets, we will fit a Cox regression with a censoring variable, with the treatment as explanatory variable and with the time to event as response variable. By taking the exponential of the coefficient associated with treatment we obtain the hazard ratio associated with the specific subgroup.

In the case of data with binary outcome, for each one of the subgroup-specific data sets, we will fit a logistic regression model with treatment as explanatory variable and with the binary considered variable as response. The coefficients associated with treatment can be interpreted as the log odds ratio associated with the specific subgroup.


### Elastic Net Penalization Model Estimation
We are going to obtain the subgroup treatment effects by fitting a model with all the available covariates and their interactions with treatment and by shrinking these interaction coefficients. The idea is to see if the different subgroups have a different treatment response from the overall population one (as we put these interaction coefficients to zero we are shrinking the subgroup treatment effect in the direction of the overall population treatment effect).

One option to shrink these coefficients is using a frequentist shrinkage model like the elastic net (ridge and lasso are special cases of it). It is important to leave the main effects unpenalized so we need to fit the model taking into account the different penalizations. Depending on the data we are going to fit a penalized Cox regression (for survival data) or a penalized logistic regression (for binary data). To obtain the subgroup treatment effects from this penalized model we need to marginalize over the different subgroups. 


### Bayesian Shrinkage Model Estimation
We are going to obtain the subgroup treatment effects by fitting a bayesian model with all the available covariates and their interactions with treatment. We are applying over these interaction coefficients a shrinkage prior while over the main effect coefficients we apply a normal prior with a wide variance (we are consider a not very informative prior). 

The shrinkage prior chosen for the interaction coefficients is the horseshoe prior as it shrinks towards zero the coefficients that are close to zero but leaves unpenalized the large coefficients. As we want to detect the large differences between subgroup-specific treatment effects and the overall population effect it is interesting that those large differences are not shrunken towards zero. 

After fitting the model we are going to have samples from the estimated posterior distribution of these coefficients. With them, after marginalizing over the different subgroups, we are going to be able to obtain the subgroup treatment effects estimates.



