---
name: 🐞 Bug Report
description: File a bug report
title: "[Bug]: <title>"
labels: ["bug"]
assignees:
  - danielinteractive
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct.](https://github.com/insightsengineering/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
  - type: checkboxes
    id: contributor-guidelines
    attributes:
      label: Contribution Guidelines
      description: By submitting this issue, you agree to follow our [Contribution Guidelines.](https://github.com/insightsengineering/.github/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Contribution Guidelines.
          required: true
  - type: checkboxes
    id: security-policy
    attributes:
      label: Security Policy
      description: By submitting this issue, you agree to follow our [Security Policy.](https://github.com/insightsengineering/.github/security/policy)
      options:
        - label: I agree to follow this project's Security Policy.
          required: true
